# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

#     generate_pdf:
#         path: /generate-pdf
#         controller: App\Controller\PdfController::generatePdf

controllers:
    resource: ../src/Controller/
    type: attribute