# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    gotenberg_url: 'http://gotenberg:3000'

services:
    # default configuration for services in *this* file
    App\Service\SymfonyDocs: ~
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\EventListener\RedirectIfNotAuthenticatedListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Controller\:
        resource: '../src/Controller'
        # Exclude non-controller files or directories if necessary
        exclude: '../src/Controller/{DependencyInjection,EventSubscriber}'

    App\Service\GotenbergService:
        arguments:
            $gotenbergUrl: '%gotenberg_url%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones